[package]
name = "prompt-mcp"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
jsonschema = "0.47.0"
serde_json.workspace = true
prompt-domain = { path = "../prompt-domain" }
prompt-store = { path = "../prompt-store" }
time.workspace = true
uuid.workspace = true

[dev-dependencies]
tempfile = "3.23.0"
